on: [push]
name: Deptrac

jobs:
  deptrac:
    name: deptrac
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: deptrac
        uses: docker://smoench/deptrac-action:latest
        with:
          args: analyse